# Generated by Django 3.1.5 on 2021-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210201_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese')], default='English', help_text='Book language', max_length=20),
        ),
    ]
