# Generated by Django 3.1.5 on 2021-02-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_create_book', 'Create book'), ('can_update_book', 'Update book'), ('can_delete_book', 'Delete book'))},
        ),
    ]
