# Generated by Django 3.1.5 on 2021-02-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210203_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language0',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
    ]
