# Generated by Django 3.1.5 on 2021-02-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210203_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language0',
        ),
    ]
