# Generated by Django 3.1.5 on 2021-02-03 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
